module ircfiber.build_version;

// Generated by scripts/generate-version.sh at 2026-08-24T15:02:55Z
enum GIT_HASH = "1a592e450c82c8ce9de4b3527f78b8a9db3cac32";
enum GIT_SHORT = "1a592e4";
enum GIT_DESCRIBE = "1a592e4";
enum GIT_BRANCH = "main";
enum BUILD_TIME = "2026-08-24T15:02:55Z";
enum BUILD_HOST = "macbook-pro.tail544547.ts.net";
enum VERSION = "0.3.0";
enum GIT_MESSAGE = "feat: workspace root Makefile + engine deploy fixes";
enum GIT_COMMIT_URL = "https://github.com/kevinpostal/ircfiber-engine/commit/1a592e450c82c8ce9de4b3527f78b8a9db3cac32";
