#!/usr/bin/env bash
# generate-version.sh — write common/source/ircfiber/build_version.d with current git info
set -eo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/common/source/ircfiber/build_version.d"

# Guard: engine repo must have engine/, must NOT have frontend/
if [ ! -d "$ROOT/engine" ]; then
  echo "generate-version.sh: expected engine/ — are you in the engine repo?" >&2
  exit 1
fi
if [ -d "$ROOT/frontend" ]; then
  echo "generate-version.sh: found frontend/ — this is the engine repo, not site" >&2
  exit 1
fi

HASH=$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo "unknown")
SHORT=$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
# describe without dirty, then add dirty suffix only if non-build_version/buildInfo files are dirty (engine only tracks build_version)
DESCRIBE_BASE=$(git -C "$ROOT" describe --always --long 2>/dev/null || echo "$SHORT")
if ! git -C "$ROOT" diff --quiet -- ':!common/source/ircfiber/build_version.d' 2>/dev/null; then DIRTY="-dirty"; fi
if ! git -C "$ROOT" diff --cached --quiet -- ':!common/source/ircfiber/build_version.d' 2>/dev/null; then DIRTY="-dirty"; fi
DESCRIBE="${DESCRIBE_BASE}${DIRTY}"
BRANCH=$(git -C "$ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "unknown")
HOST=$(hostname 2>/dev/null || echo "unknown")
VERSION="0.3.0"
# Commit subject for admin display (escaped for D/TS string literals)
RAW_MSG=$(git -C "$ROOT" log -1 --pretty=%s 2>/dev/null || echo "unknown")
# Escape backslashes and double quotes for D/TS string
ESC_MSG=$(printf '%s' "$RAW_MSG" | sed 's/\\/\\\\/g; s/"/\\"/g' | tr -d '\r\n')
if [ "$ESC_MSG" = "" ]; then ESC_MSG="unknown"; fi
COMMIT_URL=""
if [ "$HASH" != "unknown" ] && [ "$HASH" != "" ]; then COMMIT_URL="https://github.com/kevinpostal/ircfiber-engine/commit/$HASH"; fi

cat > "$OUT" <<EOV
module ircfiber.build_version;

// Generated by scripts/generate-version.sh at $TIME
enum GIT_HASH = "$HASH";
enum GIT_SHORT = "$SHORT";
enum GIT_DESCRIBE = "$DESCRIBE";
enum GIT_BRANCH = "$BRANCH";
enum BUILD_TIME = "$TIME";
enum BUILD_HOST = "$HOST";
enum VERSION = "$VERSION";
enum GIT_MESSAGE = "$ESC_MSG";
enum GIT_COMMIT_URL = "$COMMIT_URL";
EOV
echo "version.d: $SHORT ($DESCRIBE) @ $BRANCH built $TIME — $ESC_MSG"

# Engine repo has no frontend — skip buildInfo.ts generation
if [ -d "$ROOT/frontend" ]; then
  FRONT_OUT="$ROOT/frontend/src/lib/buildInfo.ts"
  cat > "$FRONT_OUT" <<EOV
// Generated by scripts/generate-version.sh at $TIME — do not edit
export const BUILD_INFO = {
  commit: "$HASH",
  short: "$SHORT",
  describe: "$DESCRIBE",
  branch: "$BRANCH",
  builtAt: "$TIME",
  builtHost: "$HOST",
  version: "$VERSION",
  message: "$ESC_MSG",
  commitUrl: "$COMMIT_URL",
} as const;
EOV
  echo "buildInfo.ts: $SHORT ($DESCRIBE) @ $BRANCH — $ESC_MSG"
else
  echo "buildInfo.ts: skipped — no frontend/ in engine repo"
fi
